# Generated by Django 4.1.7 on 2023-03-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.CharField(choices=[('0', 'CONTADOR'), ('1', 'ADMINISTRADOR'), ('2', 'ECONOMISTA'), ('3', 'DESARROLLADOR'), ('4', 'ALMACENISTA'), ('5', 'TÉCNICO'), ('6', 'ENFERMERA'), ('7', 'OTRO')], max_length=1, verbose_name='Cargo'),
        ),
    ]
