# Generated by Django 4.1.7 on 2023-04-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
    ]
